Open ExportVars, add ImportVars, add SetGroupBool
psiberx/cp2077-cet-kit pull request #3
Opened 2023-12-28 21:57 UTC by shmerl

A few modifications to allow exporting and importing variables without converting the result into a string or file.

Plus additional helper function to set all group boolean values.

This can be useful for storing settings temporarily in memory when mod needs it.

Example is a simple HUD toggle mod that saves HUD settings state, then turns them all off and then restores them.

2023-12-30 11:32 UTC, psiberx requested changes

2023-12-30 11:32 UTC, psiberx commented on GameSettings.lua
> -function module.exportVars(isPreGame, group, output)
Please keep this function as is and use it in all public functions including new `ExportVars()`.

2023-12-30 23:11 UTC, shmerl commented on GameSettings.lua
> -function module.exportVars(isPreGame, group, output)
Updated

2023-12-31 00:30 UTC, merged

2023-12-31 00:30 UTC, psiberx commented
Thank you!